# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Katrina Nicole Siegfried
# Author: Katrina Nicole Siegfried
# Note: Portions of this file were drafted/edited with AI assistance and reviewed by the author.

services:
  agentic-author:
    build:
      context: .
      dockerfile: Dockerfile
    image: agentic-author:latest
    environment:
      # Set this in your shell or a .env file (Compose auto-loads .env)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    working_dir: /app
    volumes:
      - ./agentic_author_ai/data:/app/agentic_author_ai/data
      # If you want hot-reload of code while developing:
      # - .:/app
    entrypoint: ["/usr/bin/tini", "--"]
    command: ["python", "-m", "agentic_author_ai.demo"]
